### ISSUE TITLE
News?

### ISSUE THREAD

**Issue by LobeTia** [trailsjs/doc#22]
We're in 2.0 but we still don't have a complete documentation for improving the onboarding experience for the users and solving common issues

You plan to release somethings is the next months?
In case, there's anything I can help with?

**Comment by maissani** [comment]
Hi, 
I'm working on docs, and i will release some docs in the nex couple of days. 
Help is welcome, you can check on this issue what is https://github.com/trailsjs/trails-docs/issues/5 contributors and assignation on docs. 
I was bussy for a large month because i get a large and big project to handle. 
I'm doign all things possible to contribute when i can.

**Comment by LobeTia** [comment]
Thank you for your time maissani!
Some weeks ago I was wondering about writing some pages but I wasn't sure about what is already made and not pushed/merged and what is still pending.

I think I'll wait for your release and then start integrating the missing parts.
Or maybe if nobody has still done it, I can start drafting the site generation part, just for having an MVP about page creation, asset minification, task pipelines and so on, I'm quite addicted to this kind of stuff 😉 

Let me know!

**Comment by tjwebb** [comment]
We're working on getting the trailsjs.io website up and running now. Once the docs have a place to go, we will begin publishing them.

preview: http://beta.trailsjs.io/
